apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongodb-storage-class-v2
provisioner: disk.csi.azure.com # Change to a cloud-specific provisioner if needed
parameters:
  skuName: Standard_LRS
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-v2
  # labels:
  #   type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mongodb-storage-class
  csi:
    driver: disk.csi.azure.com
    volumeHandle: /subscriptions/<subscriptiob-id>/resourceGroups/AksSimply/providers/Microsoft.Compute/disks/testdiskpv
    volumeAttributes:
      shareName: ext4

--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc-v2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: mongodb-storage-class-v2